format_version = 2

[toggle]
n = "TOGGLE"
inherit = ["t", "x", "y"]
inputs = [{n="CLK", o=1}]
gates = [
 {t="DFF", i=[1,3], o=[2,3]},
]
outputs = [{n="Q", i=2}]

[workspace]
n = "Counter / virtual silicon"
inherit = ["t", "x", "y"]
inputs = [{n="Enable", o=1}]
gates = [
 {t="CLK", o=2, p=8},
 {t="AND", i=[1,2], o=3},
 {t="TOGGLE", i=3, o=4},
 {i=4, o=5},
 {i=5, o=6},
 {i=6, o=7},
 {t="NODE", i=4, o=8, n="COUNT.Q0"},
 {i=5, o=9, n="COUNT.Q1"},
 {i=6, o=10, n="COUNT.Q2"},
 {i=7, o=11, n="COUNT.Q3"},
 {t="DISPLAY", i=[4,5,6,7], n="COUNT", x=0, y=0},
 {t="NODE", i=4, o=12, x=-90, y=120, nsh="SQUARE", non="#44DD99", nof="#173D2C"},
 {i=5, o=13, x=-30, nsh="SQUARE", non="#44DD99", nof="#173D2C"},
 {i=6, o=14, x=30, nsh="SQUARE", non="#44DD99", nof="#173D2C"},
 {i=7, o=15, x=90, nsh="SQUARE", non="#44DD99", nof="#173D2C"},
 {t="OSCILLOSCOPE", scope_channel_names=["Enable","COUNT.Q"]},
]
outputs = [{n="Carry",i=7,x=260,y=0}]
